
name: Build image and Deploy

on:
  push:
    branches: [main]
    paths: .github/workflows/main.yaml
  pull_request:
    branches:  none
  workflow_dispatch:

jobs:
  build-deploy-aks:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: ykommuri # name of Docker Hub ID
      IMAGE_NAME: myimage
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER
      
      RESOURSE_GROUP: yeshwanth-rg

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
  
    - name: Build Docker Image
      run: |
        docker build myfiles -t $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.MY_Docker_passcode }}" | docker login -u $DOCKER_REPOSITORY --password-stdin
  
    - name: Push Image to Docker Hub
      run: |
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER
           
    - name: kubernetes deploy and pods
      run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig
          kubectl cluster-info
          kubectl apply -f myapp/dep.yaml 
          kubectl get pods
